# Generated by Django 5.2 on 2025-04-23 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=300, verbose_name='Portfolyo Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('gold', 'Altın'), ('crypto', 'Kripto Para'), ('currency', 'Döviz')], max_length=50)),
                ('asset_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.userportfolio')),
            ],
        ),
    ]
