# Generated by Django 5.2 on 2025-04-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_userportfolio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
