# Generated by Django 5.2 on 2025-04-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_portfolio_amount_alter_portfolio_buy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
