# Generated by Django 5.2 on 2025-04-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_portfolio_amount_alter_portfolio_buy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='buy_price',
            field=models.CharField(max_length=255),
        ),
    ]
