# Generated by Django 5.2 on 2025-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_portfolio_amount_alter_portfolio_buy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='buy_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
