# Generated by Django 5.2 on 2025-05-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_portfolio_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
