# Generated by Django 5.2 on 2025-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_portfolio_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='buy_price',
            field=models.FloatField(),
        ),
    ]
